name: Ordino Tests
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

# For parallel Playwright tests
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2]
    steps:
      - uses: actions/checkout@v4
      - uses: ORDINO-AI-LLC/github-action@27
        with:
          test-framework: 'playwright'
          total-shards: '2'
          shard-index: '${{ matrix.shard }}'
          skip-upload: 'true'
      
      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.shard }}
          path: ordino-report/

  upload-report:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: playwright-report-*
          path: all-reports/
      
      - uses: ORDINO-AI-LLC/github-action@27
        with:
          test-framework: 'playwright'
          action-mode: 'merge-and-upload'